### ISSUE TITLE
Cannot Access oldVersion during onUpgradeNeeded

### ISSUE THREAD

**Issue by amcvega** [truqu/purescript-indexedDB#1]
By having the old version available during onUpgradeNeeded, it is possible to implement migrations of the schema. In Javascript this is can be used via `event.oldVersion` during onUpgradeNeeded. However in the API of IDBFactory, only `Database` and `Transaction` are defined for the upgrade handler. 

I propose a change to the API to include `Version` to the defined arguments. I've implemented a quick fix here to illustrate what I mean: https://github.com/amcvega/purescript-indexedDB/commit/c661294219d40ffc20594cbab640844c9fadbca6

**Comment by KtorZ** [comment]
Hi!
Good catch. This one is definitely missing. I'll align the callback with the 'onVersionChange' event's callback an wrap the `oldVersion` in a record. 

:+1:

**Comment by KtorZ** [comment]
Fixed with [v3.0.0](https://github.com/truqu/purescript-indexedDB/releases/tag/v3.0.0)

See [here](https://pursuit.purescript.org/packages/purescript-indexeddb/3.0.0/docs/Database.IndexedDB.IDBFactory#t:Callbacks) for the changes.
