### ISSUE TITLE
Update library to using purescript-aff#v4.0.2

### ISSUE THREAD

**Issue by amcvega** [truqu/purescript-indexedDB#2]
Hi,

I wanted to use your great library on a new project but noticed it wasn't working with the latest versions of a bunch of other libraries. The key dependency holding it back seemed to be purescript-aff.

I did some tinkering and I got it to build with the latest purescript-aff. However, I was not able to get the tests running to confirm that all is okay. Here's the commit with most of my changes: https://github.com/amcvega/purescript-indexedDB/commit/a95469deceb4b7337c7d547302c6fc20d3a2af83

**Comment by KtorZ** [comment]
Hey, I am not much involve with PureScript anymore (might change in the near future though) thus I am a bit out of the loop regarding updates & new versions. If it's only about a version bump, I'll try to do it in the upcoming days and see. 

I invite you to make a PR with your changes as a start :) That might come in handy!

**Comment by KtorZ** [comment]
Should be solved in 4.0.0 :+1:
